[aamXLAnimeMix_v10]
slow = 415
fast = 48
like = 0
inference = 0
style = "anime"

[albedobaseXL_v31Large]
slow = 286
fast = 56
like = 0
inference = 0
style = "real"

[epicrealismXL_pureFix]
slow = 221
fast = 54
like = 0
inference = 0
style = "real"

[pornmaster_proSDXLV8]
slow = 376
fast = 56
like = 0
inference = 0
style = "real"

[animeIllustDiffusion_v08]
slow = 345
fast = 46
like = 0
inference = 0
style = "anime"

[counterfeitxl_v25]
slow = 492
fast = 46
like = 0
inference = 0
style = ""

[protovisionXLHighFidelity3D_releaseV660Bakedvae]
slow = 476
fast = 70
like = 0
inference = 0
style = "real"

[fantasticmix_v10]
slow = 336
fast = 40
like = 0
inference = 0
style = "anime"

[realcartoonXL_v7]
slow = 394
fast = 69
like = 0
inference = 0
style = ""

[sdXL_v10VAEFix]
slow = 373
fast = 66
like = 0
inference = 0
style = ""

[sdxlNijiSeven_sdxlNijiSeven]
slow = 374
fast = 63
like = 0
inference = 0
style = "anime"

[CheckpointDarksushipdxl_v1]
slow = 766
fast = 45
like = 0
inference = 0
style = ""

[AnythingXL_xl]
slow = 484
fast = 41
like = 0
inference = 0
style = "anime"

[animagineXLV31_v31]
slow = 435
fast = 49
like = 0
inference = 0
style = ""

[cyberrealisticXL_v100]
slow = 243
fast = 65
like = 0
inference = 0
style = "real"

[bluePencilXL_v700]
slow = 703
fast = 73
like = 0
inference = 0
style = ""

[xxmix9realisticsdxl_v10]
slow = 139
fast = 67
like = 0
inference = 0
style = "real"

[reproductionSDXL_2v12]
slow = 419
fast = 100
like = 0
inference = 0
style = ""

[animeArtDiffusionXL_alpha3]
slow = 427
fast = 94
like = 0
inference = 0
style = ""

[animaPencilXL_v500]
slow = 380
fast = 92
like = 0
inference = 0
style = ""

[starlightXLAnimated_v3]
slow = 155
fast = 96
like = 0
inference = 0
style = ""

[sdvn7Nijistylexl_v1]
slow = 445
fast = 96
like = 0
inference = 0
style = ""

[stableDiffusionXL_final]
slow = 325
fast = 43
like = 0
inference = 0
style = ""

[SDXLFaetastic_v24]
slow = 526
fast = 90
like = 0
inference = 0
style = ""

[breakdomainxl_V06d]
slow = 606
fast = 102
like = 0
inference = 0
style = ""

[explicitFreedomNSFW_alpha]
slow = 423
fast = 107
like = 0
inference = 0
style = ""

[4Guofeng4XL_v12]
slow = 562
fast = 108
like = 0
inference = 0
style = ""

[animexlXuebimix_v60LCM]
slow = 205
fast = 120
like = 0
inference = 0
style = ""

[hentaiMixXLRoadTo_v50]
slow = 364
fast = 85
like = 0
inference = 0
style = ""

[kohakuXLAlpha_nyan]
slow = 554
fast = 116
like = 0
inference = 0
style = ""

[artium_v20]
slow = 641
fast = 89
like = 0
inference = 0
style = ""

[shikianimexl_v10]
slow = 484
fast = 110
like = 0
inference = 0
style = ""

[osorubeshiXL_nsfwHyperV01]
slow = 416
fast = 64
like = 0
inference = 0
style = ""

[suzannesXLMix_v80]
slow = 566
fast = 104
like = 0
inference = 0
style = ""

[kohakuXLDelta_rev1]
slow = 236
fast = 81
like = 0
inference = 0
style = ""

[kohakuXLEpsilon_rev2]
slow = 315
fast = 50
like = 0
inference = 0
style = ""

[raemuXL_v50]
slow = 425
fast = 44
like = 0
inference = 0
style = ""

[ghostxl_v10BakedVAE]
slow = 471
fast = 64
like = 0
inference = 0
style = ""

[heartOfAppleXL_v30]
slow = 312
fast = 63
like = 0
inference = 0
style = ""

[talesOfDigitalDesireSFW_v22]
slow = 307
fast = 307
like = 0
inference = 0
style = ""

[aniverseXL_v40]
slow = 495
fast = 72
like = 0
inference = 0
style = ""

[sdxlAnimeDeephentai_v132]
slow = 481
fast = 96
like = 0
inference = 0
style = ""

[colorfulxl_v70]
slow = 561
fast = 142
like = 0
inference = 0
style = ""

[grilledLamprey_sdxlV37o2n2]
slow = 342
fast = 84
like = 0
inference = 0
style = ""

[nekorayxl_v06W3]
slow = 350
fast = 63
like = 0
inference = 0
style = ""

[aniease_v25]
slow = 180
fast = 113
like = 0
inference = 0
style = ""

[animeChangefulXL_v10ReleasedCandidate]
slow = 327
fast = 89
like = 0
inference = 0
style = ""

[aingdiffusionXL_v14]
slow = 431
fast = 56
like = 0
inference = 0
style = ""

[vxpILXL_v188]
slow = 574
fast = 50
like = 0
inference = 0
style = ""

[swampmachine_v30]
slow = 388
fast = 79
like = 0
inference = 0
style = ""

[coamixxlAnim4gine_v50]
slow = 160
fast = 50
like = 0
inference = 0
style = ""

[xlMerges_xl016Bydy]
slow = 260
fast = 98
like = 0
inference = 0
style = ""

[colorfulAnimeXLXL_v20]
slow = 411
fast = 87
like = 0
inference = 0
style = ""

[nijiStyleXL_v21]
slow = 349
fast = 70
like = 0
inference = 0
style = ""

[komeAnimeColoringChibiStyle_v10]
slow = 426
fast = 83
like = 0
inference = 0
style = ""

[elMichaelXLVpred_v10]
slow = 175
fast = 77
like = 0
inference = 0
style = ""

[xlMyzyLittleFresh_v10]
slow = 598
fast = 109
like = 0
inference = 0
style = ""

[xlColorfulDimension_v10]
slow = 433
fast = 71
like = 0
inference = 0
style = ""

[xlVibratoryRollerHans_v20]
slow = 382
fast = 49
like = 0
inference = 0
style = ""

[mmdPLUSXL_v10]
slow = 526
fast = 73
like = 0
inference = 0
style = ""

[colorburstXL_animeSDXLV10]
slow = 515
fast = 116
like = 0
inference = 0
style = ""

[colorfulFantasyXL25D_v10]
slow = 473
fast = 127
like = 0
inference = 0
style = ""

[caricartoon_alpha]
slow = 525
fast = 94
like = 0
inference = 0
style = ""

[xlLightning_v10]
slow = 243
fast = 152
like = 0
inference = 0
style = ""

[xlMyzyKoreanStyle_v10]
slow = 491
fast = 137
like = 0
inference = 0
style = ""

[xlReActerMk4s_v10]
slow = 386
fast = 53
like = 0
inference = 0
style = ""

[7thAnimeXLA_v10]
slow = 296
fast = 90
like = 0
inference = 0
style = ""

[endjourneyXL_v11]
slow = 309
fast = 94
like = 0
inference = 0
style = ""

[SDXLAnimeBulldozer_v20]
slow = 696
fast = 72
like = 0
inference = 0
style = ""

[chenkinAnimeHotbaby_v20]
slow = 568
fast = 68
like = 0
inference = 0
style = ""

[raenaXL_v20]
slow = 248
fast = 44
like = 0
inference = 0
style = ""

[envyoverdrivexl_v11]
slow = 364
fast = 91
like = 0
inference = 0
style = ""

[auroraXLBasePonyXL_v10]
slow = 362
fast = 61
like = 0
inference = 0
style = ""

[confettiComradeMix_confettiComradeMix]
slow = 1158
fast = 142
like = 0
inference = 0
style = ""

[copaxMelodiesXL_v4]
slow = 398
fast = 99
like = 0
inference = 0
style = ""

[boleromixSDXL_v20Animagine4]
slow = 360
fast = 57
like = 0
inference = 0
style = ""

[vanillawareStyle_xl20]
slow = 254
fast = 50
like = 0
inference = 0
style = ""

[leosamAiartSDXL_v20]
slow = 455
fast = 170
like = 0
inference = 0
style = ""

[zavyyumexl_v10]
slow = 568
fast = 85
like = 0
inference = 0
style = ""

[shiratakimixXL_v20]
slow = 267
fast = 79
like = 0
inference = 0
style = ""

[artiwaifuDiffusion_v20]
slow = 368
fast = 50
like = 0
inference = 0
style = ""

[duchaitenNijiSDXL_v04]
slow = 667
fast = 123
like = 0
inference = 0
style = ""

[asyncsMIXXL_v32]
slow = 499
fast = 112
like = 0
inference = 0
style = ""

[kohakuXLGamma_rev2]
slow = 282
fast = 89
like = 0
inference = 0
style = ""

[infinianimexl_v16]
slow = 301
fast = 135
like = 0
inference = 0
style = ""

[cardosXL_v10]
slow = 328
fast = 165
like = 0
inference = 0
style = ""

[envyhyperrealxl01_v10BakedVae]
slow = 355
fast = 157
like = 0
inference = 0
style = ""

[x2AnimeFinal_v20]
slow = 421
fast = 69
like = 0
inference = 0
style = ""

[darkPizzaXLOriginXL_v40]
slow = 372
fast = 176
like = 0
inference = 0
style = ""

[pyrosSDModelsBlowjob_v0122022steps]
slow = 382
fast = 109
like = 0
inference = 0
style = ""

[cutecore_xlV3]
slow = 613
fast = 142
like = 0
inference = 0
style = ""

[baxlBlueArchiveFlatCelluloidStyleFineTune_xlv3]
slow = 335
fast = 78
like = 0
inference = 0
style = ""

[RealitiesEdgeXLANIME_20]
slow = 363
fast = 363
like = 0
inference = 0
style = ""

[sdxlNuclearGeneralPurposeV3Semi_v30]
slow = 375
fast = 84
like = 0
inference = 0
style = ""

[softfantasy_animeblossom]
slow = 580
fast = 100
like = 0
inference = 0
style = ""

[7thAnimeXLB_v10]
slow = 308
fast = 46
like = 0
inference = 0
style = ""

[endlessMaestroMix_apple]
slow = 473
fast = 105
like = 0
inference = 0
style = ""

[nijiflat_v02]
slow = 536
fast = 118
like = 0
inference = 0
style = ""

[urangdiffusionV31_v31]
slow = 225
fast = 51
like = 0
inference = 0
style = ""

[realisticFantasyMix_v30]
slow = 192
fast = 192
like = 0
inference = 0
style = ""

[envymegamixxl01_v30]
slow = 685
fast = 67
like = 0
inference = 0
style = ""

[reponyginexl_v1]
slow = 149
fast = 96
like = 0
inference = 0
style = ""

[hardcoreHentai_ponyV11]
slow = 442
fast = 71
like = 0
inference = 0
style = ""
family = "pony"

[ponyFaetality_v11]
slow = 438
fast = 115
like = 0
inference = 0
style = ""
family = "pony"

[incursiosMemeDiffusion_v27PDXL]
slow = 198
fast = 198
like = 0
inference = 0
style = ""
family = "pony"

[PVCStyleModelMovable_pony166R]
slow = 473
fast = 79
like = 0
inference = 0
style = ""
family = "pony"

[js2prony_v10]
slow = 302
fast = 103
like = 0
inference = 0
style = ""
family = ""

[realmixpony_v121]
slow = 451
fast = 159
like = 0
inference = 0
style = ""
family = "pony"

[snowpony_v10]
slow = 408
fast = 111
like = 0
inference = 0
style = ""
family = "pony"

[hosekiLustrousmixPony_v20]
slow = 522
fast = 142
like = 0
inference = 0
style = ""
family = "pony"

[boleromixPony_v233]
slow = 323
fast = 131
like = 0
inference = 0
style = ""
family = "pony"

[luminaversePonyXL_v10]
slow = 312
fast = 91
like = 0
inference = 0
style = ""
family = "pony"

[aniversePonyXL_v60]
slow = 346
fast = 154
like = 0
inference = 0
style = ""
family = "pony"

[fantasmPonyXL_v10]
slow = 211
fast = 47
like = 0
inference = 0
style = ""
family = "pony"

[symPonyWorld_v20]
slow = 227
fast = 69
like = 0
inference = 0
style = ""
family = "pony"

[waiANIHENTAIPONYXL_v60]
slow = 197
fast = 71
like = 0
inference = 0
style = ""
family = "pony"

[oneFORALLPonyFantasy_v20DPO]
slow = 746
fast = 104
like = 0
inference = 0
style = ""
family = "pony"

[malaAnimeMixNSFW_v70WithoutVAE]
slow = 428
fast = 65
like = 0
inference = 0
style = ""
family = ""

[momoiropony_v15]
slow = 721
fast = 107
like = 0
inference = 0
style = ""
family = "pony"

[ponyDiffusionV6XL_v6TurboDPOMerge]
slow = 289
fast = 106
like = 0
inference = 0
style = ""
family = "pony"

[cyberrealisticPony_semiRealV5]
slow = 475
fast = 145
like = 0
inference = 0
style = ""
family = "pony"

[duchaitenPonyXLNo_v70]
slow = 384
fast = 96
like = 0
inference = 0
style = ""
family = "pony"

[autismmixSDXL_autismmixPony]
slow = 599
fast = 128
like = 0
inference = 0
style = ""
family = "pony"

[tPonynai3_v7]
slow = 250
fast = 142
like = 0
inference = 0
style = ""
family = "pony"

[hassakuXLPony_v13BetterEyesVersion]
slow = 582
fast = 130
like = 0
inference = 0
style = ""
family = "pony"

[waiANIPONYXL_v140]
slow = 411
fast = 158
like = 0
inference = 0
style = ""
family = "pony"

[prefectPonyXL_v6]
slow = 437
fast = 103
like = 0
inference = 0
style = ""
family = "pony"

[rainponyxl_rainfallV2]
slow = 183
fast = 183
like = 0
inference = 0
style = ""
family = "pony"

[animeConfettiComrade_v3]
slow = 141
fast = 141
like = 0
inference = 0
style = ""
family = ""

[ceiiAnimePDXL_v12Pony]
slow = 758
fast = 758
like = 0
inference = 0
style = ""
family = "pony"

[hadrianDelicexlPony_v30a2]
slow = 210
fast = 210
like = 0
inference = 0
style = ""
family = "pony"
