prompt = "1girl or 2girl girl sexy posing. front, turn back, side, etc. free view posision."
count = 0
openpose = false
positive = "natural color, score_9, score_8, score_7"
negative = "synthesis body, lowres, bad anatomy, worst quality, extra hand, not 5-fingers, malformed body, diffrent faces upper body and under body, malformed feet, extra feet, missing feet, deformed limbs, duplicate, clone, repeated, collage, panels, grid, tiling, seamless pattern, complementary colors, duotone, two-tone, color grading, oversaturated"
cfg = 7.0
steps = 50
seed = "-1"
width = 768
height = 768
sampler = "dpmpp_2m"
scheduler = "karras"
lora_total = 0.8
adetailer = true
hires_fix = true
hires_scale = 1.5
hires_denoise = 0.35
hires_steps = 20
adetailer_person = false
checkpoint_random = true
lora_keywords = ""
arch_filter = "mix"
auto_upscale = true
auto_upscale_style = "anime"
many = true
prompt_mode = "free"
