prompt = "a standing girl peeing."
count = 50
openpose = false
positive = "natural color, score_9, score_8, score_7, look at objective or close eyes or look at viewer as much as possible"
negative = "synthesis body, lowres, bad anatomy, worst quality, extra hand, not 5-fingers, malformed body, diffrent faces upper body and under body, malformed feet, extra feet, missing feet, deformed limbs, duplicate, clone, repeated, collage, panels, grid, tiling, seamless pattern, complementary colors, duotone, two-tone, color grading, oversaturated"
cfg = 7.0
steps = 30
seed = "-1"
width = 1024
height = 1024
sampler = "dpmpp_2m"
scheduler = "karras"
lora_total = 0.8
adetailer = true
hires_fix = true
hires_scale = 1.5
hires_denoise = 0.35
hires_steps = 20
