[tensors_dirs]
list = [
    "3_1_SD15_checkpoint",
    "3_2_SD15_LoRA",
    "4_1_SDXL_checkpoint",
    "4_2_SDXL_LoRA",
]

[LoRA_preview_template]
ware = "1lady, solo, full body, weared, standing, looking at viewer, simple background"
doing1 = "1lady, solo, full body, simple background"
doing2 = "2ladies, full body, interaction, simple background"
doing3 = "3ladies, full body, interaction, simple background"
doingmob = "ladies, full body, interaction, simple background"
object = "nobody, simple background"
part = "1lady, solo, close-up, simple background"
view = "1lady, solo, full body, simple background"
place = "nobody, scenery"
artstyle = "1lady, solo, upper body, looking at viewer, detailed, simple background"
unknown = "1lady, solo, upper body, simple background"

[checkpoint_preview_template]
default = "1lady, solo, full body, weared, standing, looking at viewer, simple background"
